### ISSUE TITLE
Some questions for clarification.

### ISSUE THREAD

**Issue by debasmitdas** [varunranga/zorb-numpy#2]
Very interesting method. I have a few questions -

- Does the method work for deeper networks around 10 layers ? When implementing deeper networks, I see that activations tend to explode when doing the inverse again and again backwards.

- There is no pooling layer defined. Naturally, it causes the feature dimension to explode. Inverse of pooling is also difficult. A workaround I tried is using strided convolution. Does your implementation of backward of conv  also work on strided convolution ?

**Comment by varunranga** [comment]
1. Yes, this methods works for deeper networks (compared to BP+GD). We have run experiments in which ZORB trains 20+ sigmoid layered neural networks on MNIST without problems equivalent to vanishing/exploding gradients.
2. I have implemented forward strided convolutions, but not backward; this was done to avoid losing information in the backward pass. I assume believe backward strided (de-)convolutions can be implemented. Pooling layers needs to be defined, along with many other layers such as Attention.

**Comment by debasmitdas** [comment]
Thanks for the response. Very informative. Is there any workaround for using ZORB for ResNets ?

**Comment by varunranga** [comment]
You will need to formulate both the forward and backward passes manually. But I think it is possible, since your forward pass only changes from y = Wx + b to y = (W+1)x + b; the backward pass can be derived similar to the paper.
