### ISSUE TITLE
batch_size

### ISSUE THREAD

**Issue by ShunxianGu** [varunranga/zorb-numpy#3]
batch_size is not contained in the zorb, is it?
well ,if batch_size cannot be set in the zorb, zorb is a full-batch training. So ,  will out of memory happen?

**Comment by varunranga** [comment]
Yes, OOM is highly possible. That is why this current version is suited only for small-to-medium scale datasets.
But I have significantly upgraded this algorithm in offline versions, including a "greedy-zorb" (faster training) and a "batch-zorb" (memory constrained) by combining this algorithm with a previous algorithm (https://arxiv.org/abs/1802.00027).
